# This file created by conda-build 24.1.2
# ------------------------------------------------

package:
  name: anaconda-auth
  version: 0.8.6
source:
  git_rev: v0.8.6
  git_url: https://github.com/anaconda/anaconda-auth.git
build:
  number: 0
  script: python -m pip install . --no-deps --no-build-isolation --ignore-installed
    --no-cache-dir -vv
  string: py313h06a4308_0
requirements:
  build:
    - _libgcc_mutex 0.1 main
    - _openmp_mutex 5.1 1_gnu
    - bzip2 1.0.8 h5eee18b_6
    - c-ares 1.19.1 h5eee18b_0
    - ca-certificates 2025.2.25 h06a4308_0
    - curl 8.12.1 h251f7ec_0
    - expat 2.7.1 h6a678d5_0
    - gettext 0.21.0 hedfda30_2
    - git 2.45.2 pl5340h9abc3c3_1
    - icu 73.1 h6a678d5_0
    - krb5 1.20.1 h143b758_1
    - libcurl 8.12.1 hc9e6f67_0
    - libedit 3.1.20230828 h5eee18b_0
    - libev 4.33 h7f8727e_1
    - libgcc-ng 11.2.0 h1234567_1
    - libgomp 11.2.0 h1234567_1
    - libnghttp2 1.57.0 h2d74bed_0
    - libssh2 1.11.1 h251f7ec_0
    - libstdcxx-ng 11.2.0 h1234567_1
    - libxml2 2.13.8 hfdd30dd_0
    - lz4-c 1.9.4 h6a678d5_1
    - ncurses 6.4 h6a678d5_0
    - openssl 3.0.16 h5eee18b_0
    - pcre2 10.42 hebb0a14_1
    - perl 5.40.2 0_h5eee18b_perl5
    - tk 8.6.14 h39e8969_0
    - xz 5.6.4 h5eee18b_1
    - zlib 1.2.13 h5eee18b_1
    - zstd 1.5.6 hc292b87_0
  host:
    - _libgcc_mutex 0.1 main
    - _openmp_mutex 5.1 1_gnu
    - bzip2 1.0.8 h5eee18b_6
    - ca-certificates 2025.2.25 h06a4308_0
    - expat 2.7.1 h6a678d5_0
    - hatch-vcs 0.4.0 py313h06a4308_0
    - hatchling 1.27.0 py313h06a4308_0
    - ld_impl_linux-64 2.40 h12ee557_0
    - libffi 3.4.4 h6a678d5_1
    - libgcc-ng 11.2.0 h1234567_1
    - libgomp 11.2.0 h1234567_1
    - libmpdec 4.0.0 h5eee18b_0
    - libstdcxx-ng 11.2.0 h1234567_1
    - libuuid 1.41.5 h5eee18b_0
    - ncurses 6.4 h6a678d5_0
    - openssl 3.0.16 h5eee18b_0
    - packaging 24.2 py313h06a4308_0
    - pathspec 0.10.3 py313h06a4308_0
    - pip 25.1 pyhc872135_2
    - pluggy 1.5.0 py313h06a4308_0
    - python 3.13.2 hf623796_100_cp313
    - python_abi 3.13 0_cp313
    - readline 8.2 h5eee18b_0
    - setuptools 78.1.1 py313h06a4308_0
    - setuptools-scm 8.3.1 py313h06a4308_0
    - sqlite 3.45.3 h5eee18b_0
    - tk 8.6.14 h39e8969_0
    - trove-classifiers 2024.10.14 py313h06a4308_0
    - tzdata 2025b h04d1e81_0
    - wheel 0.45.1 py313h06a4308_0
    - xz 5.6.4 h5eee18b_1
    - zlib 1.2.13 h5eee18b_1
  run:
    - anaconda-cli-base >=0.5.2
    - cryptography >=3.4.0
    - keyring
    - pkce
    - pydantic
    - pyjwt
    - python >=3.13,<3.14.0a0
    - python-dotenv
    - python_abi 3.13.* *_cp313
    - requests
    - semver <4
  run_constrained:
    - anaconda-cloud-auth >=0.8.2
    - conda >=23.9.0
    - conda-token >=0.6.0
test:
  commands:
    - pip check
    - python -c "from anaconda_auth import __version__; assert __version__ == '0.8.6'"
  imports:
    - anaconda_auth
  requires:
    - pip
  source_files:
    - pyproject.toml
about:
  description: 'A client library for Anaconda.cloud APIs to authenticate and securely
    store API keys.

    This package also provides a requests client class that handles loading the API
    key

    for requests made to Anaconda Cloud services.

    '
  dev_url: https://github.com/anaconda/anaconda-auth
  doc_url: https://anaconda.github.io/anaconda-auth/
  home: https://anaconda.com
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: A client auth library for Anaconda.cloud APIs
extra:
  copy_test_source_files: true
  final: true
  flow_run_id: d8303072-fc3b-478f-a3dc-05947e139e35
  recipe-maintainers:
    - albertdefusco
    - mattkram
  remote_url: git@github.com:AnacondaRecipes/anaconda-cloud-auth-feedstock.git
  sha: db12db92c88b355fa8f6b25ac8fc36ee80b0703d
