# This file created by conda-build 24.1.2
# meta.yaml template originally from:
# /feedstock/recipe, last modified Fri Jan 10 20:26:18 2025
# ------------------------------------------------

package:
  name: semver
  version: 3.0.2
source:
  fn: semver-3.0.2.tar.gz
  sha256: 6253adb39c70f6e51afed2fa7152bcd414c411286088fb4b9effb133885ab4cc
  url: https://pypi.io/packages/source/s/semver/semver-3.0.2.tar.gz
build:
  number: '1'
  script: python -m pip install --no-deps --ignore-installed . --no-build-isolation
  string: py313h06a4308_1
requirements:
  host:
    - _libgcc_mutex 0.1 main
    - _openmp_mutex 5.1 1_gnu
    - bzip2 1.0.8 h5eee18b_6
    - ca-certificates 2024.12.31 h06a4308_0
    - expat 2.6.4 h6a678d5_0
    - ld_impl_linux-64 2.40 h12ee557_0
    - libffi 3.4.4 h6a678d5_1
    - libgcc-ng 11.2.0 h1234567_1
    - libgomp 11.2.0 h1234567_1
    - libmpdec 4.0.0 h5eee18b_0
    - libstdcxx-ng 11.2.0 h1234567_1
    - libuuid 1.41.5 h5eee18b_0
    - ncurses 6.4 h6a678d5_0
    - openssl 3.0.15 h5eee18b_0
    - pip 24.2 py313h06a4308_0
    - python 3.13.1 hf623796_100_cp313
    - python_abi 3.13 0_cp313
    - readline 8.2 h5eee18b_0
    - setuptools 75.1.0 py313h06a4308_0
    - sqlite 3.45.3 h5eee18b_0
    - tk 8.6.14 h39e8969_0
    - tzdata 2024b h04d1e81_0
    - wheel 0.44.0 py313h06a4308_0
    - xz 5.4.6 h5eee18b_1
    - zlib 1.2.13 h5eee18b_1
  run:
    - python >=3.13,<3.14.0a0
    - python_abi 3.13.* *_cp313
test:
  commands:
    - pip check
    - pytest -vv tests
  imports:
    - semver
  requires:
    - pip
    - pytest
  source_files:
    - tests/
about:
  description: 'A Python module for semantic versioning. Simplifies comparing versions.

    '
  dev_url: https://github.com/k-bx/python-semver
  doc_url: https://github.com/k-bx/python-semver
  home: https://github.com/k-bx/python-semver
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: Python package to work with Semantic Versioning
extra:
  copy_test_source_files: true
  final: true
  flow_run_id: daffc351-6a06-4d3b-8482-1c12f45a5f9d
  recipe-maintainers:
    - carlodri
    - rmax
  remote_url: git@github.com:AnacondaRecipes/semver-feedstock.git
  sha: 9c7d21db536d4313a435d9343665e6df8fb2b382
