# This file created by conda-build 24.1.2
# meta.yaml template originally from:
# /io/buildout/aggregate/pyjwt-feedstock/recipe, last modified Thu Feb 13 19:59:36 2025
# ------------------------------------------------

package:
  name: pyjwt
  version: 2.10.1
source:
  sha256: 3cc5772eb20009233caf06e9d8a0577824723b44e6648ee0a2aedb6cf9381953
  url: https://pypi.io/packages/source/p/pyjwt/pyjwt-2.10.1.tar.gz
build:
  number: '0'
  script: /io/buildout/croot/pyjwt_1739558969999/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold/bin/python
    -m pip install . --no-deps --no-build-isolation --ignore-installed --no-cache-dir
    -vv
  string: py313h06a4308_0
requirements:
  host:
    - _libgcc_mutex 0.1 main
    - _openmp_mutex 5.1 1_gnu
    - bzip2 1.0.8 h5eee18b_6
    - ca-certificates 2024.12.31 h06a4308_0
    - expat 2.6.4 h6a678d5_0
    - ld_impl_linux-64 2.40 h12ee557_0
    - libffi 3.4.4 h6a678d5_1
    - libgcc-ng 11.2.0 h1234567_1
    - libgomp 11.2.0 h1234567_1
    - libmpdec 4.0.0 h5eee18b_0
    - libstdcxx-ng 11.2.0 h1234567_1
    - libuuid 1.41.5 h5eee18b_0
    - ncurses 6.4 h6a678d5_0
    - openssl 3.0.15 h5eee18b_0
    - pip 25.0 py313h06a4308_0
    - python 3.13.2 hf623796_100_cp313
    - python_abi 3.13 0_cp313
    - readline 8.2 h5eee18b_0
    - setuptools 75.8.0 py313h06a4308_0
    - sqlite 3.45.3 h5eee18b_0
    - tk 8.6.14 h39e8969_0
    - tzdata 2025a h04d1e81_0
    - wheel 0.45.1 py313h06a4308_0
    - xz 5.6.4 h5eee18b_1
    - zlib 1.2.13 h5eee18b_1
  run:
    - python >=3.13,<3.14.0a0
    - python_abi 3.13.* *_cp313
  run_constrained:
    - cryptography >=3.4.0
test:
  commands:
    - pip check
    - pytest tests
  imports:
    - jwt
  requires:
    - pip
    - pytest >=6.0.0,<7.0.0
  source_files:
    - tests
about:
  description: 'PyJWT is a Python library which allows you to encode and decode JSON
    Web Tokens (JWT).

    JWT is an open, industry-standard (RFC 7519) for representing claims securely
    between two parties.

    '
  dev_url: https://github.com/jpadilla/pyjwt
  doc_url: https://pyjwt.readthedocs.io
  home: https://github.com/jpadilla/pyjwt
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: JSON Web Token implementation in Python
extra:
  copy_test_source_files: true
  final: true
  recipe-maintainers:
    - ocefpaf
    - pmlandwehr
